<?php

if (!defined("ABSPATH")) {
    exit;
}

function upsellio_get_definitions_dataset()
{
    return [
        [
            "slug" => "seo",
            "term" => "SEO",
            "main_keyword" => "seo co to jest",
            "secondary_keywords" => ["optymalizacja seo", "pozycjonowanie stron", "widocznosc organiczna"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["on-page-seo", "off-page-seo", "crawl-budget", "core-web-vitals"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "sem",
            "term" => "SEM",
            "main_keyword" => "sem definicja",
            "secondary_keywords" => ["search engine marketing", "reklamy w wyszukiwarce", "kampanie platne"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "latwy",
            "related_slugs" => ["ppc", "cpc", "quality-score", "ctr"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "ppc",
            "term" => "PPC",
            "main_keyword" => "ppc co to",
            "secondary_keywords" => ["pay per click", "kampania ppc", "model rozliczenia reklamy"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "latwy",
            "related_slugs" => ["cpc", "ctr", "quality-score", "roas"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "cpc",
            "term" => "CPC",
            "main_keyword" => "cpc co to",
            "secondary_keywords" => ["cost per click", "koszt klikniecia", "stawki reklamowe"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "latwy",
            "related_slugs" => ["ppc", "ctr", "quality-score", "cpm"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "cpm",
            "term" => "CPM",
            "main_keyword" => "cpm co to",
            "secondary_keywords" => ["cost per mille", "koszt tysiaca wyswietlen", "model rozliczen reklamy"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "latwy",
            "related_slugs" => ["cpc", "cpv", "ctr", "remarketing"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "cpv",
            "term" => "CPV",
            "main_keyword" => "cpv definicja",
            "secondary_keywords" => ["cost per view", "koszt obejrzenia", "kampanie wideo"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "sredni",
            "related_slugs" => ["cpm", "ctr", "view-through-conversion", "remarketing"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "ctr",
            "term" => "CTR",
            "main_keyword" => "ctr co to jest",
            "secondary_keywords" => ["click through rate", "wspolczynnik klikalnosci", "jak liczyc ctr"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "latwy",
            "related_slugs" => ["wzgledny-ctr", "cpc", "quality-score", "konwersja"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "wzgledny-ctr",
            "term" => "Wzgledny CTR",
            "main_keyword" => "wzgledny ctr",
            "secondary_keywords" => ["relative ctr", "jak obliczyc wzgledny ctr", "konkurencyjnosc reklam"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "sredni",
            "related_slugs" => ["ctr", "quality-score", "share-of-voice", "impression-share"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "quality-score",
            "term" => "Quality Score",
            "main_keyword" => "quality score co to",
            "secondary_keywords" => ["wynik jakosci reklamy", "google ads quality score", "ocena reklamy"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "sredni",
            "related_slugs" => ["ctr", "cpc", "landing-page", "intencja-wyszukiwania"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "roas",
            "term" => "ROAS",
            "main_keyword" => "roas co to",
            "secondary_keywords" => ["return on ad spend", "rentownosc reklam", "jak liczyc roas"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "latwy",
            "related_slugs" => ["roi", "cpa", "konwersja", "lifetime-value"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "roi",
            "term" => "ROI",
            "main_keyword" => "roi definicja",
            "secondary_keywords" => ["zwrot z inwestycji", "jak liczyc roi", "rentownosc dzialan marketingowych"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "latwy",
            "related_slugs" => ["roas", "cpa", "lifetime-value", "konwersja"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "cpa",
            "term" => "CPA",
            "main_keyword" => "cpa co to",
            "secondary_keywords" => ["cost per acquisition", "koszt pozyskania klienta", "jak obnizyc cpa"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "sredni",
            "related_slugs" => ["cpc", "roas", "konwersja", "lifetime-value"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "konwersja",
            "term" => "Konwersja",
            "main_keyword" => "konwersja definicja",
            "secondary_keywords" => ["czym jest konwersja", "mikro i makro konwersje", "cel kampanii"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "latwy",
            "related_slugs" => ["wspolczynnik-konwersji", "cpa", "landing-page", "cta"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "wspolczynnik-konwersji",
            "term" => "Wspolczynnik konwersji",
            "main_keyword" => "wspolczynnik konwersji",
            "secondary_keywords" => ["conversion rate", "jak zwiekszyc konwersje", "cro"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "sredni",
            "related_slugs" => ["konwersja", "cro", "landing-page", "ab-testy"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "cro",
            "term" => "CRO",
            "main_keyword" => "cro co to",
            "secondary_keywords" => ["conversion rate optimization", "optymalizacja konwersji", "testy ux"],
            "search_intent" => "informacyjna",
            "category" => "ux",
            "difficulty" => "sredni",
            "related_slugs" => ["wspolczynnik-konwersji", "ab-testy", "landing-page", "cta"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "ab-testy",
            "term" => "A/B testy",
            "main_keyword" => "ab testy",
            "secondary_keywords" => ["testy ab landing page", "eksperymenty marketingowe", "optymalizacja konwersji"],
            "search_intent" => "informacyjna",
            "category" => "ux",
            "difficulty" => "sredni",
            "related_slugs" => ["cro", "landing-page", "cta", "wspolczynnik-konwersji"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "landing-page",
            "term" => "Landing Page",
            "main_keyword" => "landing page co to",
            "secondary_keywords" => ["strona ladowania", "landing page pod reklamy", "jak projektowac landing page"],
            "search_intent" => "informacyjna",
            "category" => "ux",
            "difficulty" => "latwy",
            "related_slugs" => ["cta", "cro", "quality-score", "konwersja"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "cta",
            "term" => "CTA",
            "main_keyword" => "cta co to",
            "secondary_keywords" => ["call to action", "wezwanie do dzialania", "skuteczne cta"],
            "search_intent" => "informacyjna",
            "category" => "ux",
            "difficulty" => "latwy",
            "related_slugs" => ["landing-page", "cro", "konwersja", "ux-writing"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "ux-writing",
            "term" => "UX Writing",
            "main_keyword" => "ux writing",
            "secondary_keywords" => ["mikrocopy", "teksty interfejsu", "copy pod konwersje"],
            "search_intent" => "informacyjna",
            "category" => "ux",
            "difficulty" => "sredni",
            "related_slugs" => ["cta", "landing-page", "cro", "customer-journey"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "customer-journey",
            "term" => "Customer Journey",
            "main_keyword" => "customer journey definicja",
            "secondary_keywords" => ["sciezka klienta", "etapy decyzji zakupowej", "mapowanie journey"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "sredni",
            "related_slugs" => ["lejek-sprzedazowy", "ux-writing", "remarketing", "atrybucja"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "lejek-sprzedazowy",
            "term" => "Lejek sprzedazowy",
            "main_keyword" => "lejek sprzedazowy",
            "secondary_keywords" => ["funnel marketingowy", "etapy lejka", "top middle bottom funnel"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "latwy",
            "related_slugs" => ["customer-journey", "remarketing", "lead-magnet", "konwersja"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "lead-magnet",
            "term" => "Lead Magnet",
            "main_keyword" => "lead magnet co to",
            "secondary_keywords" => ["pozyskiwanie leadow", "material za kontakt", "formularz leadowy"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "sredni",
            "related_slugs" => ["lejek-sprzedazowy", "lead-scoring", "landing-page", "marketing-automation"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "lead-scoring",
            "term" => "Lead Scoring",
            "main_keyword" => "lead scoring",
            "secondary_keywords" => ["ocena leadow", "kwalifikacja leadow", "priorytetyzacja kontaktow"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "trudny",
            "related_slugs" => ["lead-magnet", "marketing-automation", "crm", "lifetime-value"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "marketing-automation",
            "term" => "Marketing Automation",
            "main_keyword" => "marketing automation co to",
            "secondary_keywords" => ["automatyzacja marketingu", "workflowy marketingowe", "nurturing leadow"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "trudny",
            "related_slugs" => ["lead-scoring", "crm", "email-marketing", "customer-journey"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "crm",
            "term" => "CRM",
            "main_keyword" => "crm definicja",
            "secondary_keywords" => ["system crm", "zarzadzanie relacjami z klientami", "pipeline sprzedazowy"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "sredni",
            "related_slugs" => ["lead-scoring", "marketing-automation", "lifetime-value", "atrybucja"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "email-marketing",
            "term" => "Email Marketing",
            "main_keyword" => "email marketing co to",
            "secondary_keywords" => ["kampanie mailowe", "newsletter", "automatyzacja email"],
            "search_intent" => "informacyjna",
            "category" => "content",
            "difficulty" => "latwy",
            "related_slugs" => ["marketing-automation", "lead-magnet", "open-rate", "ctr"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "open-rate",
            "term" => "Open Rate",
            "main_keyword" => "open rate",
            "secondary_keywords" => ["wspolczynnik otwarc", "jak zwiekszyc open rate", "email performance"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "latwy",
            "related_slugs" => ["email-marketing", "ctr", "segmentacja", "ab-testy"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "segmentacja",
            "term" => "Segmentacja",
            "main_keyword" => "segmentacja klientow",
            "secondary_keywords" => ["segmentacja odbiorcow", "targetowanie kampanii", "persony"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "sredni",
            "related_slugs" => ["persona", "customer-journey", "remarketing", "email-marketing"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "persona",
            "term" => "Persona",
            "main_keyword" => "persona marketingowa",
            "secondary_keywords" => ["buyer persona", "profil klienta idealnego", "grupa docelowa"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "latwy",
            "related_slugs" => ["segmentacja", "intencja-wyszukiwania", "customer-journey", "content-marketing"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "intencja-wyszukiwania",
            "term" => "Intencja wyszukiwania",
            "main_keyword" => "intencja wyszukiwania",
            "secondary_keywords" => ["search intent", "intencja informacyjna", "intencja transakcyjna"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["slowa-kluczowe", "seo", "quality-score", "content-marketing"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "slowa-kluczowe",
            "term" => "Slowa kluczowe",
            "main_keyword" => "slowa kluczowe",
            "secondary_keywords" => ["keyword research", "frazy seo", "dobor slow kluczowych"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["long-tail", "intencja-wyszukiwania", "seo", "on-page-seo"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "long-tail",
            "term" => "Long Tail",
            "main_keyword" => "long tail seo",
            "secondary_keywords" => ["frazy dlugiego ogona", "long tail keywords", "niszowe zapytania"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["slowa-kluczowe", "seo", "content-marketing", "topical-authority"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "on-page-seo",
            "term" => "On-Page SEO",
            "main_keyword" => "on page seo",
            "secondary_keywords" => ["optymalizacja on page", "seo on site", "meta title h1"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["off-page-seo", "meta-title", "meta-description", "core-web-vitals"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "off-page-seo",
            "term" => "Off-Page SEO",
            "main_keyword" => "off page seo",
            "secondary_keywords" => ["seo off site", "link building", "autorytet domeny"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["on-page-seo", "link-building", "backlink", "domain-authority"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "meta-title",
            "term" => "Meta Title",
            "main_keyword" => "meta title co to",
            "secondary_keywords" => ["title tag", "tytul seo", "jak pisac meta title"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["meta-description", "on-page-seo", "ctr", "snippety"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "meta-description",
            "term" => "Meta Description",
            "main_keyword" => "meta description co to",
            "secondary_keywords" => ["opis seo", "jak pisac meta description", "opis wyszukiwania"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["meta-title", "ctr", "snippety", "on-page-seo"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "snippety",
            "term" => "Snippety",
            "main_keyword" => "snippety google",
            "secondary_keywords" => ["fragment rozszerzony", "rich snippets", "wyniki wyszukiwania"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["schema", "meta-title", "meta-description", "ctr"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "schema",
            "term" => "Schema",
            "main_keyword" => "schema org",
            "secondary_keywords" => ["dane strukturalne", "schema markup", "json ld"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "trudny",
            "related_slugs" => ["snippety", "faq-schema", "breadcrumbs", "seo"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "faq-schema",
            "term" => "FAQ Schema",
            "main_keyword" => "faq schema",
            "secondary_keywords" => ["faqpage schema", "faq rich results", "dane strukturalne faq"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["schema", "snippety", "faq", "content-marketing"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "breadcrumbs",
            "term" => "Breadcrumbs",
            "main_keyword" => "breadcrumbs seo",
            "secondary_keywords" => ["okruszki", "nawigacja breadcrumb", "breadcrumblist schema"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["schema", "crawl-budget", "linkowanie-wewnetrzne", "ux"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "crawl-budget",
            "term" => "Crawl Budget",
            "main_keyword" => "crawl budget",
            "secondary_keywords" => ["budzet indeksowania", "optymalizacja crawl budget", "boty google"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "trudny",
            "related_slugs" => ["indeksowanie", "robots-txt", "sitemap-xml", "linkowanie-wewnetrzne"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "indeksowanie",
            "term" => "Indeksowanie",
            "main_keyword" => "indeksowanie strony",
            "secondary_keywords" => ["jak dziala indeksowanie", "google index", "problemy indeksacji"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "sredni",
            "related_slugs" => ["crawl-budget", "robots-txt", "sitemap-xml", "kanonical"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "robots-txt",
            "term" => "Robots.txt",
            "main_keyword" => "robots txt",
            "secondary_keywords" => ["plik robots", "blokowanie robotow", "disallow allow"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "sredni",
            "related_slugs" => ["indeksowanie", "crawl-budget", "sitemap-xml", "kanonical"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "sitemap-xml",
            "term" => "Sitemap XML",
            "main_keyword" => "sitemap xml",
            "secondary_keywords" => ["mapa strony xml", "google search console sitemap", "indeksowanie adresow"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "latwy",
            "related_slugs" => ["indeksowanie", "robots-txt", "crawl-budget", "kanonical"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "kanonical",
            "term" => "Canonical",
            "main_keyword" => "canonical tag",
            "secondary_keywords" => ["tag kanoniczny", "duplikacja tresci", "rel canonical"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "sredni",
            "related_slugs" => ["indeksowanie", "on-page-seo", "sitemap-xml", "crawl-budget"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "core-web-vitals",
            "term" => "Core Web Vitals",
            "main_keyword" => "core web vitals",
            "secondary_keywords" => ["lcp cls inp", "wydajnosc strony", "web vitals seo"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "trudny",
            "related_slugs" => ["pagespeed", "seo-techniczne", "on-page-seo", "ux"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "pagespeed",
            "term" => "PageSpeed",
            "main_keyword" => "pagespeed co to",
            "secondary_keywords" => ["google pagespeed insights", "szybkosc strony", "optymalizacja wydajnosci"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "sredni",
            "related_slugs" => ["core-web-vitals", "lcp", "cls", "inp"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "lcp",
            "term" => "LCP",
            "main_keyword" => "lcp co to",
            "secondary_keywords" => ["largest contentful paint", "optymalizacja lcp", "web vitals lcp"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "trudny",
            "related_slugs" => ["core-web-vitals", "pagespeed", "cls", "inp"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "cls",
            "term" => "CLS",
            "main_keyword" => "cls co to",
            "secondary_keywords" => ["cumulative layout shift", "stabilnosc ukladu", "web vitals cls"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "trudny",
            "related_slugs" => ["core-web-vitals", "pagespeed", "lcp", "inp"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "inp",
            "term" => "INP",
            "main_keyword" => "inp co to",
            "secondary_keywords" => ["interaction to next paint", "responsywnosc strony", "web vitals inp"],
            "search_intent" => "informacyjna",
            "category" => "seo-techniczne",
            "difficulty" => "trudny",
            "related_slugs" => ["core-web-vitals", "pagespeed", "lcp", "cls"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "link-building",
            "term" => "Link Building",
            "main_keyword" => "link building co to",
            "secondary_keywords" => ["pozyskiwanie linkow", "profil linkowy", "off page seo"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["backlink", "domain-authority", "off-page-seo", "anchor-text"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "backlink",
            "term" => "Backlink",
            "main_keyword" => "backlink definicja",
            "secondary_keywords" => ["link przychodzacy", "odnosniki do strony", "jakosc backlinkow"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["link-building", "anchor-text", "domain-authority", "nofollow"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "anchor-text",
            "term" => "Anchor Text",
            "main_keyword" => "anchor text",
            "secondary_keywords" => ["tekst kotwicy", "typy anchorow", "linkowanie seo"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "latwy",
            "related_slugs" => ["backlink", "link-building", "nofollow", "linkowanie-wewnetrzne"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "nofollow",
            "term" => "Nofollow",
            "main_keyword" => "nofollow co to",
            "secondary_keywords" => ["rel nofollow", "ugc sponsored", "link juice"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["backlink", "anchor-text", "domain-authority", "link-building"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "domain-authority",
            "term" => "Domain Authority",
            "main_keyword" => "domain authority",
            "secondary_keywords" => ["autorytet domeny", "jak zwiekszyc authority", "moc domeny"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["link-building", "backlink", "off-page-seo", "topical-authority"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "topical-authority",
            "term" => "Topical Authority",
            "main_keyword" => "topical authority",
            "secondary_keywords" => ["autorytet tematyczny", "klastry tresci", "content hubs"],
            "search_intent" => "informacyjna",
            "category" => "content",
            "difficulty" => "trudny",
            "related_slugs" => ["content-marketing", "long-tail", "linkowanie-wewnetrzne", "seo"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "content-marketing",
            "term" => "Content Marketing",
            "main_keyword" => "content marketing",
            "secondary_keywords" => ["marketing tresci", "strategia contentowa", "plan tresci seo"],
            "search_intent" => "informacyjna",
            "category" => "content",
            "difficulty" => "latwy",
            "related_slugs" => ["topical-authority", "evergreen-content", "intencja-wyszukiwania", "seo-copywriting"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "evergreen-content",
            "term" => "Evergreen Content",
            "main_keyword" => "evergreen content",
            "secondary_keywords" => ["tresc ponadczasowa", "artykuly evergreen", "dlugoterminowy ruch seo"],
            "search_intent" => "informacyjna",
            "category" => "content",
            "difficulty" => "sredni",
            "related_slugs" => ["content-marketing", "topical-authority", "seo-copywriting", "snippety"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "seo-copywriting",
            "term" => "SEO Copywriting",
            "main_keyword" => "seo copywriting",
            "secondary_keywords" => ["copy pod seo", "pisanie tresci seo", "teksty na strone"],
            "search_intent" => "informacyjna",
            "category" => "content",
            "difficulty" => "sredni",
            "related_slugs" => ["content-marketing", "intencja-wyszukiwania", "cta", "on-page-seo"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "remarketing",
            "term" => "Remarketing",
            "main_keyword" => "remarketing co to",
            "secondary_keywords" => ["retargeting", "kampanie remarketingowe", "odzyskiwanie uzytkownikow"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "latwy",
            "related_slugs" => ["lejek-sprzedazowy", "customer-journey", "view-through-conversion", "frequency-capping"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "view-through-conversion",
            "term" => "View Through Conversion",
            "main_keyword" => "view through conversion",
            "secondary_keywords" => ["konwersja po wyswietleniu", "vta", "atrybucja wyswietlen"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "trudny",
            "related_slugs" => ["remarketing", "atrybucja", "cpv", "konwersja"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "frequency-capping",
            "term" => "Frequency Capping",
            "main_keyword" => "frequency capping",
            "secondary_keywords" => ["limit czestotliwosci reklam", "czestotliwosc wyswietlen", "kontrola ekspozycji"],
            "search_intent" => "informacyjna",
            "category" => "sem",
            "difficulty" => "sredni",
            "related_slugs" => ["remarketing", "cpm", "view-through-conversion", "impression-share"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "impression-share",
            "term" => "Impression Share",
            "main_keyword" => "impression share",
            "secondary_keywords" => ["udzial w wyswietleniach", "utracony udzial", "widocznosc reklamy"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "sredni",
            "related_slugs" => ["share-of-voice", "wzgledny-ctr", "frequency-capping", "quality-score"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "share-of-voice",
            "term" => "Share of Voice",
            "main_keyword" => "share of voice",
            "secondary_keywords" => ["sov marketing", "udzial glosu marki", "widocznosc marki online"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "sredni",
            "related_slugs" => ["impression-share", "wzgledny-ctr", "brand-awareness", "seo"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "brand-awareness",
            "term" => "Brand Awareness",
            "main_keyword" => "brand awareness",
            "secondary_keywords" => ["swiadomosc marki", "kampanie zasiegowe", "budowanie marki"],
            "search_intent" => "informacyjna",
            "category" => "strategia",
            "difficulty" => "latwy",
            "related_slugs" => ["share-of-voice", "cpm", "remarketing", "customer-journey"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "atrybucja",
            "term" => "Atrybucja",
            "main_keyword" => "atrybucja konwersji",
            "secondary_keywords" => ["modele atrybucji", "last click data driven", "przypisywanie konwersji"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "trudny",
            "related_slugs" => ["view-through-conversion", "customer-journey", "ga4", "konwersja"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "ga4",
            "term" => "GA4",
            "main_keyword" => "ga4 co to",
            "secondary_keywords" => ["google analytics 4", "wdrozenie ga4", "analiza ruchu"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "sredni",
            "related_slugs" => ["atrybucja", "konwersja", "utm", "eventy"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "utm",
            "term" => "UTM",
            "main_keyword" => "parametry utm",
            "secondary_keywords" => ["tagowanie linkow", "utm source medium campaign", "analiza kampanii"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "latwy",
            "related_slugs" => ["ga4", "atrybucja", "eventy", "konwersja"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "eventy",
            "term" => "Eventy",
            "main_keyword" => "eventy ga4",
            "secondary_keywords" => ["zdarzenia analytics", "tracking eventow", "pomiar mikrokonwersji"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "sredni",
            "related_slugs" => ["ga4", "utm", "konwersja", "cro"],
            "service_links" => ["/#uslugi", "/#kontakt"],
        ],
        [
            "slug" => "lifetime-value",
            "term" => "Lifetime Value",
            "main_keyword" => "lifetime value",
            "secondary_keywords" => ["ltv", "wartosc klienta w czasie", "jak liczyc ltv"],
            "search_intent" => "informacyjna",
            "category" => "analityka",
            "difficulty" => "trudny",
            "related_slugs" => ["roas", "roi", "cpa", "crm"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
        [
            "slug" => "linkowanie-wewnetrzne",
            "term" => "Linkowanie wewnetrzne",
            "main_keyword" => "linkowanie wewnetrzne seo",
            "secondary_keywords" => ["internal linking", "struktura linkow", "jak linkowac podstrony"],
            "search_intent" => "informacyjna",
            "category" => "seo",
            "difficulty" => "sredni",
            "related_slugs" => ["breadcrumbs", "topical-authority", "crawl-budget", "anchor-text"],
            "service_links" => ["/#uslugi", "/#kontakt", "/miasta/"],
        ],
    ];
}

